### PR TITLE
Add helm action to clock in task

### PR DESCRIPTION
**Pull request by PrestanceDesign**
Hi,

This my first contrib with my use case. I added an helm action to clock in on a task, maybe this can be useful for someone else.

Best regards.
Mike

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Mike,

This is a very cool idea!  I made a few adjustments, and it seems to be working well, but please let me know if I broke anything, haha.  I also added entries to the readme.  Thanks very much for sending this in!

**Comment by PrestanceDesign** [comment]
Hi Alphapapa,

You're welcome ! Thx to you for this nice package !
Perfect! Your code is more efficient and cleaner (I'm new Emacs user and learn Lisp from 2 month :)).

**Comment by alphapapa** [comment]
You're doing great for being so new to Emacs!  Keep it up!

**Comment by PrestanceDesign** [comment]
Thx ! It's because I falling in love for Emacs through Spacemacs. :)
I'm motivated 💯 👍

**Pull request closed without merging**
